# Generated by Django 5.2.14 on 2026-05-26 07:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('series', 'Series'), ('movie', 'Movie')], default='series', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RequiredLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('season_number', models.PositiveIntegerField(blank=True, null=True)),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=50)),
                ('telegram_message_link', models.TextField()),
                ('storage_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('storage_message_id', models.BigIntegerField(blank=True, null=True)),
                ('download_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('deep_link', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='movies.content')),
            ],
            options={
                'ordering': ['content', 'season_number', 'episode_number', 'quality'],
            },
        ),
        migrations.CreateModel(
            name='RequiredLinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('telegram_user_id', models.BigIntegerField()),
                ('item_code', models.CharField(max_length=255)),
                ('is_opened', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('required_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='movies.requiredlink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
